- hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: install packages
    yum: name={{item}} state=present
    loop:
    - git
    - docker
    - tomcat
  - name: Start packages
    service: name={{item}} state=started
    loop:
    - docker
    - tomcat
  - name: Deploy a WAR file
    COPY: src= addressbook.war dest=/usr/share/tomcat/webapps
    notify: Restart tomcat
  handlers:
  - name: Restart tomcat
    service: name=tomcat state=restarted
  
